Repository gardener/gardener-extension-provider-aws, pull requests merged in 2020-10, with the labels that each got.

#191 Adding additional test definition provider-aws-extended
  .test-defs/provider-aws-extended.yaml
Labels: kind/enhancement, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm

#192 Update amazon/aws-ebs-csi-driver to v0.7.0
  charts/images.yaml
Labels: area/storage, kind/task, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm

#195 Upgrade github.com/gardener/machine-controller-manager
  charts/images.yaml
Labels: area/performance, kind/bug, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm

#193 Changing the default parameters handling and adding all properties to the test definition
  .test-defs/provider-aws-extended.yaml
  .test-defs/provider-aws.yaml
  test/tm/generator.go
Labels: kind/enhancement, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm

#196 Enhance extension's chart values
  Dockerfile
  charts/gardener-extension-provider-aws/templates/deployment.yaml
  charts/gardener-extension-provider-aws/templates/vpa.yaml
  charts/gardener-extension-provider-aws/values.yaml
  docs/usage-as-end-user.md
  example/controller-registration.yaml
Labels: area/documentation, area/robustness, kind/enhancement, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/xs

#197 Add k8s 1.19 conformance tests (testgrid) links
  README.md
Labels: kind/enhancement, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/xs

#201 Upgrade github.com/gardener/cloud-provider-aws
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#202 add priority class for extension pods
  charts/gardener-extension-provider-aws/templates/_helpers.tpl
  charts/gardener-extension-provider-aws/templates/deployment.yaml
  charts/gardener-extension-provider-aws/templates/priorityclass.yaml
  example/controller-registration.yaml
Labels: area/high-availability, kind/enhancement, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/xs

#204 Nit: Do no longer ignore deprecated item usage
  .golangci.yaml
Labels: area/dev-productivity, kind/cleanup, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/xs
