Repository gardener/gardener-extension-provider-aws, pull requests merged in 2020-11, with the labels that each got.

#200 Landscaper component
  .landscaper/blueprint.yaml
  .landscaper/deploy_items.yaml
  .landscaper/imports.yaml
  .landscaper/registration/Chart.yaml
  .landscaper/registration/templates/cloudprofile.yaml
  .landscaper/registration/templates/controllerregistration.yaml
  .landscaper/registration/templates/secrets.yaml
  .landscaper/registration/values.yaml
Labels: area/delivery, area/open-source, kind/enhancement, needs/changes, needs/ok-to-test, needs/second-opinion, platform/aws, priority/normal, size/xl

#205 Revendor gardener/gardener@v1.12.3, update to golang@1.15.3 and alpine@3.12.1
  .test-defs/infrastructure-test.yaml
  .test-defs/provider-aws.yaml
  Dockerfile
  charts/gardener-extension-provider-aws/templates/_images.tpl
  example/controller-registration.yaml
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/config.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/terraformer.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/types.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/helper/shootstate_list.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/controllerutils/miscellaneous.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/addons.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/botanist.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/clusterautoscaler/cluster_autoscaler.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubecontrollermanager/kube_controller_manager.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubecontrollermanager/logging.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubecontrollermanager/monitoring.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubecontrollermanager/monitoring_alertingrules.test.yaml
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubecontrollermanager/shoot_resources.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubecontrollermanager/waiter.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubescheduler/kube_scheduler.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/monitoring.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/secrets.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/waiter.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/wanted_secrets.go
  vendor/github.com/gardener/gardener/pkg/operation/common/utils.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/github.com/gardener/gardener/pkg/operation/shoot/types.go
  vendor/github.com/gardener/gardener/pkg/operation/shootsecrets/secrets_manager.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/taskfn.go
  vendor/modules.txt
Labels: area/control-plane, kind/cleanup, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/xs

#206 Fix "make test" on macOS
  go.mod
  go.sum
  vendor/github.com/gobuffalo/packr/v2/SHOULDERS.md
  vendor/github.com/gobuffalo/packr/v2/go.mod
  vendor/github.com/gobuffalo/packr/v2/go.sum
  vendor/github.com/gobuffalo/packr/v2/version.go
  vendor/github.com/karrick/godirwalk/bench.sh
  vendor/github.com/karrick/godirwalk/readdir_unix.go
  vendor/github.com/karrick/godirwalk/scandir_unix.go
  vendor/modules.txt
Labels: area/dev-productivity, kind/bug, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/xs

#209 Document rate limit issues
  docs/usage-as-end-user.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#210 Error wrapping for UpdateMachineImagesStatus function
  pkg/controller/worker/machine_images.go
Labels: area/logging, kind/enhancement, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/xs

#216 Inject infrastructure credentials via secret references
  go.mod
  go.sum
  pkg/controller/infrastructure/actuator.go
  pkg/controller/infrastructure/actuator_delete.go
  pkg/controller/infrastructure/actuator_migrate.go
  pkg/controller/infrastructure/actuator_reconcile.go
  test/integration/infrastructure/infrastructure_test.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/config.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/terraformer.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/types.go
  vendor/github.com/gardener/gardener/hack/.ci/prepare_release
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/addons.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/types.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/constraints_check.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/clusterautoscaler/bootstrap.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/etcd/bootstrap.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/etcd/etcd.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/etcd/monitoring.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/dns.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/health_check.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/systemcomponents/metricsserver/metrics_server.go
  vendor/github.com/gardener/gardener/pkg/operation/common/types.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/health/health.go
  vendor/github.com/gardener/gardener/test/framework/dump.go
  vendor/github.com/gardener/gardener/test/framework/shootframework.go
  vendor/github.com/golang/snappy/AUTHORS
  vendor/github.com/golang/snappy/CONTRIBUTORS
  vendor/github.com/golang/snappy/decode.go
  vendor/github.com/golang/snappy/decode_arm64.s
  vendor/github.com/golang/snappy/decode_asm.go
  vendor/github.com/golang/snappy/decode_other.go
  vendor/github.com/golang/snappy/encode.go
  vendor/github.com/golang/snappy/encode_arm64.s
  vendor/github.com/golang/snappy/encode_asm.go
  vendor/github.com/golang/snappy/encode_other.go
  vendor/modules.txt
Labels: area/quality, area/security, kind/cleanup, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/s

#219 Prepare Next Dev Cycle v1.17.1-dev
  VERSION
  example/controller-registration.yaml
Labels: area/delivery, kind/impediment, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/xs

#220 Cherrypick PR#218 to release-v1.17
  charts/images.yaml
Labels: area/dev-productivity, kind/regression, needs/ok-to-test, platform/aws, priority/critical, reviewed/lgtm, size/xs

#221 Prepare Next Dev Cycle v1.16.1-dev
  VERSION
  example/controller-registration.yaml
Labels: area/delivery, kind/impediment, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/xs

#222 Bump MCM version from 0.34.3 to 0.34.4
  charts/images.yaml
Labels: area/dev-productivity, kind/regression, needs/ok-to-test, platform/aws, priority/critical, reviewed/lgtm, size/xs

#224 Update docker images to use GCR copy for release-v1.16
  Dockerfile
Labels: area/dev-productivity, kind/impediment, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/xs

#225 Revert "Update docker images to use GCR copy for release-v1.16"
  Dockerfile
Labels: area/dev-productivity, kind/regression, needs/ok-to-test, platform/aws, priority/normal, size/xs

#228 Bump MCM version from 0.35.1 to 0.35.2
  charts/images.yaml
Labels: kind/bug, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/xs

#229 Run infra integration test on release
  .ci/pipeline_definitions
  .ci/test-integration.sh
  .ci/testruns/default/Chart.yaml
  .ci/testruns/default/templates/testrun.yaml
  .ci/tm-config.yaml
Labels: area/quality, kind/enhancement, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/s
