Repository gardener/gardener-extension-provider-aws, pull requests merged in 2020-06, with the labels that each got.

#105 Support multiple EBS disks and encryption when creating machines
  docs/usage-as-end-user.md
  example/30-worker.yaml
  pkg/apis/aws/validation/shoot.go
  pkg/apis/aws/validation/shoot_test.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: area/storage, kind/enhancement, needs/ok-to-test, needs/review, platform/aws, priority/normal

#110 [cherry-pick 103] Add missing Service for cloud-controller-manager
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/deployment.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/service.yaml
  pkg/controller/controlplane/valuesprovider.go
Labels: area/monitoring, kind/bug, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm

#113 [ci:component:github.com/gardener/terraformer:v1.0.0->v1.1.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#111 Adapt to terrafom v0.12 language changes
  charts/internal/aws-infra/templates/main.tf
  charts/internal/aws-infra/templates/variables.tf
  charts/internal/aws-infra/values.yaml
  pkg/controller/infrastructure/actuator_reconcile.go
Labels: kind/cleanup, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm

#115 Vendor gardener/gardener@b50098267f2577d06674903fa20032f1fe44894b
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/backupentry/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/infrastructure/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/reconciler.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/validation/seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/istio/ingress_gateway.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/types.go
  vendor/modules.txt
Labels: area/open-source, kind/bug, needs/ok-to-test, platform/aws, priority/normal

#116 [ci:component:github.com/gardener/machine-controller-manager:v0.29.0->v0.30.0]
  charts/images.yaml
Labels: needs/ok-to-test

#112 Support for data volume IOPS + snapshot ID
  Dockerfile
  charts/internal/machineclass/values.yaml
  docs/usage-as-end-user.md
  example/30-worker.yaml
  hack/api-reference/api.md
  pkg/apis/aws/helper/helper.go
  pkg/apis/aws/helper/helper_test.go
  pkg/apis/aws/types_worker.go
  pkg/apis/aws/v1alpha1/types_worker.go
  pkg/apis/aws/v1alpha1/zz_generated.conversion.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/aws/validation/infrastructure.go
  pkg/apis/aws/validation/shoot.go
  pkg/apis/aws/validation/shoot_test.go
  pkg/apis/aws/validation/worker.go
  pkg/apis/aws/validation/worker_test.go
  pkg/apis/aws/zz_generated.deepcopy.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
  pkg/validator/shoot_validator.go
Labels: area/storage, kind/enhancement, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm

#117 Prevent panic when the worker has no providerConfig
  pkg/apis/aws/validation/shoot.go
  pkg/apis/aws/validation/shoot_test.go
Labels: area/quality, kind/bug, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm

#119 Move cleanup logic in AfterSuite
  test/integration/infrastructure/infrastructure_test.go
Labels: kind/enhancement, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm

#124 Wait for terraformer before deleting infrastructure
  go.mod
  go.sum
  pkg/controller/infrastructure/actuator_delete.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/config.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/state.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/types.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/waiter.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/defaults.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/health_check.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/patch.go
Labels: area/quality, area/robustness, kind/bug, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm

#125 :sparkle: Enable default SSE for s3 bucket
  pkg/aws/client/client.go
Labels: area/security, kind/enhancement, needs/ok-to-test, platform/aws, priority/critical, reviewed/lgtm

#127 [ci:component:github.com/gardener/terraformer:v1.1.0->v1.2.0]
  charts/images.yaml
Labels: needs/ok-to-test

#128 [ci:component:github.com/gardener/machine-controller-manager:v0.30.0->v0.31.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#130 Remove NoExecute toleration from CCM and LB readvertiser
  charts/internal/aws-lb-readvertiser/templates/aws-lb-readvertiser.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/deployment.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm

#132 Delete running terraformer Pods before deleting infrastructure
  pkg/controller/infrastructure/actuator_delete.go
Labels: area/quality, area/robustness, kind/bug, needs/ok-to-test, needs/review, platform/aws, priority/normal

#131 add rolling update strategy to deployment
  charts/gardener-extension-provider-aws/templates/deployment.yaml
  charts/gardener-extension-provider-aws/values.yaml
  example/controller-registration.yaml
Labels: kind/technical-debt, needs/ok-to-test, platform/aws, priority/normal

#135 Specify that v1.10 and v1.11 are no longer actively tested
  README.md
Labels: area/documentation, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm

#136 [ci:component:github.com/gardener/terraformer:v1.2.0->v1.3.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm
