Repository gardener/gardener-extension-provider-aws, pull requests merged in 2021-07, with the labels that each got.

#366 Update kubernetes-csi/external-snapshotter
  charts/images.yaml
  charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotclasses.yaml
  charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotcontents.yaml
  charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshots.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xl

#369 Set minAllowed memory for csi-driver-node containers
  charts/internal/aws-lb-readvertiser/templates/aws-lb-readvertiser-vpa.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
Labels: area/storage, area/testing, kind/bug, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#371 Nit: Remove redundant import
  cmd/gardener-extension-provider-aws/app/app.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#373 [release-v1.25] Automated cherry pick of #369: Set minAllowed memory for csi-driver-node containers
  charts/internal/aws-lb-readvertiser/templates/aws-lb-readvertiser-vpa.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
Labels: area/storage, area/testing, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#372 Document limitation about encryption with customer managed CMKs
  docs/usage-as-end-user.md
Labels: area/documentation, needs/ok-to-test, needs/review, size/xs

#376 Update aws-ebs-csi-driver
  charts/images.yaml
Labels: area/storage, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#374 Clean up handling for unsupported K8s versions
  README.md
  charts/gardener-extension-provider-aws/templates/_helpers.tpl
  charts/internal/aws-lb-readvertiser/charts/utils-templates/templates/_versions.tpl
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/_helpers.tpl
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/configmap-observability.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/deployment.yaml
  charts/internal/shoot-storageclasses/templates/_helpers.tpl
  charts/internal/shoot-storageclasses/templates/storageclasses_legacy.yaml
  example/10-fake-shoot-controlplane.yaml
  example/30-controlplane.yaml
  example/30-controlplaneexposure.yaml
  example/30-worker.yaml
  example/controller-registration.yaml
  pkg/controller/controlplane/valuesprovider_test.go
Labels: kind/cleanup, needs/ok-to-test, platform/aws, reviewed/lgtm, size/s

#381 Vendor gardener/gardener@v1.27.1
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/hack/.ci/prepare_release
  vendor/github.com/gardener/gardener/hack/test-cover-clean.sh
  vendor/github.com/gardener/gardener/hack/test-cover.sh
  vendor/github.com/gardener/gardener/hack/test-integration.sh
  vendor/github.com/gardener/gardener/hack/test-prometheus.sh
  vendor/github.com/gardener/gardener/hack/test.sh
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#379 Add dnsrecord integration test
  .ci/testruns/default/templates/testrun.yaml
  .test-defs/dnsrecord-test.yaml
  Makefile
  pkg/aws/client/client_route53.go
  test/integration/dnsrecord/dnsrecord_suite_test.go
  test/integration/dnsrecord/dnsrecord_test.go
Labels: area/control-plane, kind/test, merge/squash, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xl

#383 Update kubernetes-csi/external-provisioner
  charts/images.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-deployment.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-provisioner.yaml
Labels: area/storage, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs
