Repository gardener/gardener-extension-provider-aws, pull requests merged in 2021-04, with the labels that each got.

#311 Fix the infrastructure-test TestDefinition
  .test-defs/infrastructure-test.yaml
  .test-defs/provider-aws.yaml
  Dockerfile
Labels: kind/bug, kind/test, needs/ok-to-test, reviewed/lgtm, size/xs

#309 Update kubernetes-csi/external-snapshotter
  charts/images.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#312 Increase revisionHistoryLimit
  charts/gardener-extension-admission-aws/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-provider-aws/templates/deployment.yaml
  charts/internal/aws-lb-readvertiser/templates/aws-lb-readvertiser.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/deployment.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-deployment.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-controller-deployment.yaml
  example/controller-registration.yaml
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#314 Update .ci/pipeline_definitions
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, reviewed/lgtm, size/xs

#313 Specify container resources for CSI sidecars
  charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
Labels: kind/enhancement, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#320 Update aws-ebs-csi-driver
  charts/images.yaml
  pkg/admission/validator/webhook.go
Labels: area/storage, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#321 Use VPC ID from InfrastructureConfig if possible
  pkg/controller/infrastructure/actuator_delete.go
  test/integration/infrastructure/infrastructure_test.go
Labels: area/ops-productivity, kind/bug, kind/test, merge/squash, needs/ok-to-test, platform/aws, reviewed/lgtm, size/s

#322 Adapt the IAM policy for terraformer-provider-aws >= 3.29.1
  docs/usage-as-end-user.md
Labels: needs/lgtm, needs/ok-to-test, needs/review, platform/aws, size/xs

#326 Decrease terraformer log level
  pkg/controller/infrastructure/actuator.go
Labels: kind/test, needs/ok-to-test, reviewed/lgtm, size/xs

#324 Update ClusterRoles for MCM
  charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
Labels: area/dev-productivity, kind/enhancement, kind/test, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#325 Add integration test case for invalid credentials
  test/integration/infrastructure/infrastructure_test.go
Labels: area/usability, kind/test, needs/ok-to-test, platform/aws, reviewed/lgtm, size/s
