Repository gardener/gardener-extension-provider-aws, pull requests merged in 2021-02, with the labels that each got.

#266 Cherrypick of PR#265 on release-v1.20
  charts/images.yaml
Labels: area/usability, kind/regression, needs/ok-to-test, needs/review, platform/aws, priority/normal, reviewed/do-not-merge, size/xs

#269 Vendor gardener/gardener@v1.16.1
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#270 [release-v1.20] Vendor gardener/gardener@v1.16.1
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#272 Clean up the stale target build stage
  Dockerfile
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#273 Vendor gardener/gardener@v1.16.2
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/modules.txt
Labels: area/ops-productivity, kind/bug, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/xs

#275 [release-v1.20] Vendor gardener/gardener@v1.16.2
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/modules.txt
Labels: area/ops-productivity, kind/bug, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/xs

#276 [release-v1.20] Upgrade github_com_gardener_machine-controller-manager-provider-aws from v0.4.0 to v0.4.1
  charts/images.yaml
Labels: area/ops-productivity, kind/bug, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/xs

#271 VPA for validator/admission component
  charts/gardener-extension-admission-aws/charts/runtime/templates/vpa.yaml
  charts/gardener-extension-admission-aws/values.yaml
Labels: area/auto-scaling, area/scalability, kind/enhancement, needs/ok-to-test, platform/aws, priority/normal, reviewed/lgtm, size/s

#278 Update kubernetes-csi/external-snapshotter to v2.1.4
  charts/images.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#281 Switch to kaniko oci builder
  .ci/pipeline_definitions
  Dockerfile
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#283 Fix the erroneous pipeline definition
  .ci/pipeline_definitions
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs
