Repository gardener/gardener-extension-provider-aws, pull requests merged in 2021-05, with the labels that each got.

#327 Create landscaper component
  .ci/component_descriptor
  .landscaper/blueprint.yaml
  .landscaper/blueprint/blueprint.yaml
  .landscaper/blueprint/deploy-execution-manifests.yaml
  .landscaper/deploy_items.yaml
  .landscaper/imports.yaml
  .landscaper/registration/Chart.yaml
  .landscaper/registration/templates/cloudprofile.yaml
  .landscaper/registration/templates/controllerregistration.yaml
  .landscaper/registration/templates/secrets.yaml
  .landscaper/registration/values.yaml
  .landscaper/resources.yaml
Labels: area/delivery, needs/changes, needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#330 Allow controller to access Bastions
  charts/gardener-extension-provider-aws/templates/rbac.yaml
  example/controller-registration.yaml
Labels: area/open-source, kind/bug, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#332 Replace aws-infra Helm chart with native Go templates
  charts/internal/aws-infra/Chart.yaml
  charts/internal/aws-infra/templates/_helpers.tpl
  charts/internal/aws-infra/templates/terraform.tfvars
  charts/internal/aws-infra/templates/variables.tf
  charts/internal/aws-infra/values.yaml
  go.mod
  pkg/controller/infrastructure/actuator.go
  pkg/controller/infrastructure/actuator_reconcile.go
  pkg/controller/infrastructure/actuator_restore.go
  pkg/controller/infrastructure/templates/main.tpl.tf
  pkg/controller/infrastructure/terraform.go
  test/integration/bastion/bastion_test.go
  test/integration/infrastructure/infrastructure_test.go
  vendor/modules.txt
Labels: area/open-source, kind/cleanup, kind/test, needs/ok-to-test, platform/aws, reviewed/lgtm, size/l

#335 [GEP-15] fix wrong base64 encoding for bastion instance userdata
  pkg/controller/bastion/actuator_reconcile.go
  test/integration/bastion/bastion_test.go
Labels: area/ops-productivity, kind/bug, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#331 Allow to specify IAM instance profiles on workers
  charts/images.yaml
  charts/internal/machineclass/templates/machineclass.yaml
  charts/internal/machineclass/values.yaml
  docs/usage-as-end-user.md
  example/30-worker.yaml
  hack/api-reference/api.md
  pkg/apis/aws/types_worker.go
  pkg/apis/aws/v1alpha1/types_worker.go
  pkg/apis/aws/v1alpha1/zz_generated.conversion.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/aws/validation/worker.go
  pkg/apis/aws/validation/worker_test.go
  pkg/apis/aws/zz_generated.deepcopy.go
  pkg/aws/types.go
  pkg/controller/infrastructure/actuator_reconcile.go
  pkg/controller/worker/machine_images.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: area/usability, kind/api-change, kind/enhancement, kind/test, merge/squash, needs/ok-to-test, platform/aws, reviewed/lgtm, size/l

#336 Add validation for cloud provider Secrets
  charts/gardener-extension-admission-aws/charts/application/templates/validatingwebhook-validator.yaml
  cmd/gardener-extension-admission-aws/app/app.go
  docs/local-setup.md
  example/40-validatingwebhookconfiguration.yaml
  hack/dev-setup-admission-aws.sh
  pkg/admission/cmd/options.go
  pkg/admission/validator/secrets.go
  pkg/admission/validator/shoot.go
  pkg/admission/validator/webhook.go
  pkg/apis/aws/validation/secrets.go
  pkg/apis/aws/validation/secrets_test.go
  vendor/github.com/gardener/gardener/extensions/pkg/util/index/index.go
  vendor/github.com/gardener/gardener/extensions/pkg/util/secret/secret.go
  vendor/modules.txt
Labels: area/ops-productivity, area/robustness, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/lgtm, size/l

#340 [release-v1.24] Prepare for next release cycle v1.24.1-dev
  VERSION
  example/controller-registration.yaml
Labels: area/delivery, kind/cleanup, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#342 [release-v1.24] Automated cherry pick of #339: [ci:component:github.com/gardener/machine-controller-manager-provider-aws:v0.5.0->v0.7.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#341 [release-v1.24] Automated cherry pick of #338: [ci:component:github.com/gardener/machine-controller-manager:v0.38.0->v0.39.0]
  charts/images.yaml
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#344 Vendor gardener/gardener@v1.23.1
  example/controller-registration.yaml
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/charts/images.yaml
  vendor/github.com/gardener/gardener/hack/generate-controller-registration.sh
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types.go
  vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#346 Update the admission-aws RBAC after cloud provider Secrets validation feature
  charts/gardener-extension-admission-aws/charts/application/templates/rbac.yaml
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#345 Expose logs from user exposed components in the new way
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/configmap-observability.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/configmap-observability.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#347 Reduce the verbosity of csi-driver-node logs
  charts/images.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
