Repository gardener/gardener-extension-provider-aws, pull requests merged in 2021-11, with the labels that each got.

#438 [release-v1.29] Automated cherry pick of #421: Increase cpu resources for csi-driver
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
Labels: area/robustness, area/storage, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#440 Add Kubernetes v1.22 conformance badge
  README.md
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, area/testing

#434 Add validation for non-existing and already wrongly-associated EIPs
  pkg/aws/client/client.go
  pkg/aws/client/mock/mocks.go
  pkg/aws/client/types.go
  pkg/controller/infrastructure/configvalidator.go
  pkg/controller/infrastructure/configvalidator_test.go
Labels: area/quality, needs/ok-to-test, platform/aws, reviewed/lgtm, size/m

#447 [release-v1.30] Automated cherry pick of #440: Add Kubernetes v1.22 conformance badge
  README.md
Labels: kind/enhancement, needs/ok-to-test, needs/review, size/xs, area/testing

#446 Add docforge manifest
  .docforge/manifest.yaml
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/lgtm, needs/review, platform/aws, size/xs

#445 Add `srcAndDstChecksEnabled` to the MachineClass template
  charts/internal/machineclass/templates/machineclass.yaml
Labels: area/quality, kind/bug, needs/ok-to-test, needs/review, platform/aws, size/xs

#448 Improve the error message when a required part of webhookConfig is missing
  charts/gardener-extension-admission-aws/charts/application/templates/validatingwebhook-validator.yaml
  charts/gardener-extension-admission-aws/charts/runtime/templates/secret-cert.yaml
Labels: area/quality, kind/bug, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#449 Updated cluster creation tutorial - AWS
  docs/tutorials/kubernetes-cluster-on-aws-with-gardener/_index.md
  docs/tutorials/kubernetes-cluster-on-aws-with-gardener/images/processing-cluster.png
Labels: area/documentation, kind/enhancement, platform/aws, reviewed/lgtm, size/xs

#452 [ci:component:github.com/gardener/terraformer:v2.12.0->v2.12.1]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#453 Enable volume encryption by default
  charts/gardener-extension-provider-aws/templates/storageclass.yaml
  charts/gardener-extension-provider-aws/values.yaml
  charts/internal/shoot-storageclasses/templates/storageclasses.yaml
  charts/internal/shoot-storageclasses/templates/storageclasses_legacy.yaml
  example/controller-registration.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs
