Repository gardener/gardener-extension-provider-aws, pull requests merged in 2022-02, with the labels that each got.

#490 Vendor gardener/gardener@v1.39.4
  example/20-crd-extensions.gardener.cloud_bastions.yaml
  go.mod
  go.sum
  pkg/controller/bastion/actuator_reconcile.go
  test/integration/bastion/bastion_test.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_restore.go
  vendor/github.com/gardener/gardener/pkg/apis/core/helper/helpers.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_bastion.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/extensions/crds/templates/crd-bastion.tpl.yaml
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/secrets.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#467 🛡 Enable `ServiceAccount` token projection and token requestor
  Makefile
  charts/gardener-extension-provider-aws/templates/deployment.yaml
  charts/gardener-extension-provider-aws/templates/serviceaccount.yaml
  charts/gardener-extension-provider-aws/values.yaml
  charts/internal/aws-lb-readvertiser/templates/aws-lb-readvertiser.yaml
  charts/internal/aws-lb-readvertiser/values.yaml
  charts/internal/cloud-controller-manager/templates/cloud-controller-manager-svc.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/machine-controller-manager/seed/templates/serviceaccount.yaml
  charts/internal/machine-controller-manager/seed/values.yaml
  charts/internal/machine-controller-manager/shoot/templates/clusterrolebinding-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/values.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/configmap-observability.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/deployment.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-deployment.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-controller-deployment.yaml
  charts/internal/seed-controlplane/values.yaml
  charts/internal/shoot-system-components/charts/cloud-controller-manager/templates/rbac-cloud-controller-manager.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrolebinding-csi-attacher.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrolebinding-csi-provisioner.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrolebinding-csi-resizer.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrolebinding-csi-snapshotter.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrolebinding-snapshot-controller.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/rolebinding-csi-attacher.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/rolebinding-csi-provisioner.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/rolebinding-csi-resizer.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/rolebinding-csi-snapshotter.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/rolebinding-snapshot-controller.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/serviceaccount.yaml
  charts/internal/shoot-system-components/values.yaml
  cmd/gardener-extension-provider-aws/app/app.go
  example/controller-registration.yaml
  pkg/controller/controlplane/add.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
  pkg/controller/worker/actuator.go
  pkg/controller/worker/add.go
Labels: area/security, kind/enhancement, needs/ok-to-test, needs/rebase, needs/review, needs/second-opinion, size/xl, merge/squash

#487 Add support for sa token volume projection in admission charts
  charts/gardener-extension-admission-aws/charts/application/templates/rbac.yaml
  charts/gardener-extension-admission-aws/charts/application/templates/serviceaccount.yaml
  charts/gardener-extension-admission-aws/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-aws/charts/runtime/templates/serviceaccount.yaml
  charts/gardener-extension-admission-aws/values.yaml
  docs/deployment.md
Labels: area/security, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/m

#472 allow gateway endpoints for domain names
  pkg/apis/aws/validation/infrastructure.go
  pkg/apis/aws/validation/infrastructure_test.go
Labels: area/networking, kind/api-change, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#494 Vendor gardener/gardener@v1.40.1
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/update.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#495 [release-v1.33] Vendor gardener/gardener@v1.39.5
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/update.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#496 Update valuesprovider.go
  pkg/controller/controlplane/valuesprovider.go
Labels: needs/ok-to-test, reviewed/lgtm

#498 Fix serviceaccount defaulting during helm upgrade
  charts/gardener-extension-admission-aws/charts/runtime/templates/deployment.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#501 Keep `cloud-controller-manager`'s `ClusterRoleBinding` on deletion
  charts/internal/shoot-system-components/charts/cloud-controller-manager/templates/rbac-cloud-controller-manager.yaml
Labels: area/usability, kind/bug, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#504 Vendor gardener/gardener@v1.40.2
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_restore.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#503 Improve grafana dashboards
  charts/internal/machine-controller-manager/seed/mcm-monitoring-dashboard.json
  charts/internal/seed-controlplane/charts/cloud-controller-manager/ccm-dashboard.json
  charts/internal/seed-controlplane/charts/csi-driver-controller/csi-driver-controller-dashboard.json
Labels: area/monitoring, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xl, merge/squash
