Repository gardener/gardener-extension-provider-aws, pull requests merged in 2022-04, with the labels that each got.

#528 Move `Name` field to `ControlPlaneSecretConfig`
  pkg/controller/controlplane/valuesprovider.go
Labels: area/open-source, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#533 [release-v1.34] Fix ControlPlane exposure reconciliation
  pkg/controller/controlplane/valuesprovider.go
Labels: area/quality, kind/bug, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#535 Fix incorrect validator deployment value
  charts/gardener-extension-admission-aws/charts/runtime/templates/deployment.yaml
Labels: area/control-plane, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#537 add k8s v1.23 conformance testgrid link
  README.md
Labels: area/certification, kind/test, platform/aws, reviewed/lgtm, size/xs

#517 Update manifest.yaml
  .docforge/manifest.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#534 Remove deprecated dashboards
  charts/internal/seed-controlplane/charts/cloud-controller-manager/ccm-dashboard.json
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/configmap-observability.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/csi-driver-controller-dashboard.json
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/configmap-observability.yaml
Labels: area/logging, kind/cleanup, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xl
