Repository gardener/gardener-extension-provider-aws, pull requests merged in 2022-01, with the labels that each got.

#469 `make generate` for the year change
  pkg/apis/aws/v1alpha1/zz_generated.conversion.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/aws/v1alpha1/zz_generated.defaults.go
  pkg/apis/aws/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
Labels: needs/ok-to-test

#474 [release-v1.32] Automated cherry pick of #469: `make generate` for the year change
  pkg/apis/aws/v1alpha1/zz_generated.conversion.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/aws/v1alpha1/zz_generated.defaults.go
  pkg/apis/aws/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#473 Increase aws_route_table creation timeout from 2m to 5m
  pkg/controller/infrastructure/templates/main.tpl.tf
Labels: area/quality, kind/bug, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#475 [release-v1.32] Automated cherry pick of #473: Increase aws_route_table creation timeout from 2m to 5m
  pkg/controller/infrastructure/templates/main.tpl.tf
Labels: area/quality, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#480 Support for Kubernetes v1.23
  README.md
  charts/images.yaml
  pkg/webhook/controlplane/ensurer.go
  pkg/webhook/controlplane/ensurer_test.go
Labels: area/open-source, area/usability, exp/intermediate, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/m, topology/garden, topology/seed, topology/shoot, merge/squash

#470 Update RBAC for leader election of machine-controller-manager
  charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#471 Update aws-ebs-csi-driver to `v1.5.0`
  charts/images.yaml
Labels: needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#479 Kubernetes Version Configurability per Worker Pool
  docs/usage-as-end-user.md
  pkg/admission/validator/shoot.go
  pkg/apis/aws/validation/shoot.go
  pkg/apis/aws/validation/shoot_test.go
  pkg/webhook/controlplane/ensurer.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, needs/rebase, needs/review, platform/aws, size/m, merge/squash

#459 Add check for the docforge manifest
  .ci/verify
  .gitignore
  Makefile
  hack/tools/bin/.gitkeep
Labels: area/documentation, kind/enhancement, needs/changes, needs/review, platform/aws, reviewed/ok-to-test, size/xs

#481 Fix the infrastructure integration test
  test/integration/infrastructure/infrastructure_test.go
Labels: kind/regression, needs/ok-to-test, platform/aws, reviewed/lgtm, reviewed/do-not-merge, size/xs, area/testing

#486 Fix instance terminated check
  pkg/controller/bastion/actuator_delete.go
Labels: area/quality, kind/bug, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs
