Repository gardener/gardener-extension-provider-aws, pull requests merged in 2023-06, with the labels that each got.

#761 Align the aws_internet_gateway timeout to terraformer's timeout
  pkg/controller/infrastructure/templates/main.tpl.tf
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#763 update `aws-csi-volume-modifier` in vpa
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-vpa.yaml
Labels: area/robustness, kind/bug, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#764 [release-v1.44] Automated cherry pick of #763: update `aws-csi-volume-modifier` in vpa
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-vpa.yaml
Labels: area/robustness, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#766 Fix S3 bucket policy for different AWS partitions (region groups)
  pkg/aws/client/client.go
Labels: area/backup, kind/bug, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#767 Improve msg when validating cidrs
  pkg/apis/aws/validation/infrastructure.go
  pkg/apis/aws/validation/infrastructure_test.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#765 Remove old and obsolete logging configurations
  charts/gardener-extension-provider-aws/templates/clusterfilters-logging.yaml
  charts/gardener-extension-provider-aws/templates/clusterparsers-logging.yaml
  charts/gardener-extension-provider-aws/templates/configmap-logging.yaml
  example/controller-registration.yaml
Labels: area/logging, kind/cleanup, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/m

#769 [release-v1.44] Automated cherry pick of #766: Fix S3 bucket policy for different AWS partitions (region groups)
  pkg/aws/client/client.go
Labels: area/backup, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#768 Patch external-provisioner to 3.4.1
  charts/images.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, needs/review, platform/aws, size/xs

#752 Clean up ignored volumesnapshot CRDs
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/crd-volumesnapshotclasses.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/crd-volumesnapshotcontents.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/crd-volumesnapshots.yaml
Labels: area/storage, kind/cleanup, needs/ok-to-test, needs/review, needs/second-opinion, platform/aws, size/xl

#776 [release-v1.44] Automated cherry pick of #775: Upgrade machine-controller-manager
  charts/images.yaml
Labels: area/ops-productivity, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#777 [release-v1.44] Vendor gardener/gardener@v1.71.5
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/terraformer.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/controllerutils/miscellaneous.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/managedseed.go
  vendor/modules.txt
Labels: area/ops-productivity, kind/bug, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#773 Drop code related to `APIServerSNI` feature gate
  pkg/webhook/controlplaneexposure/ensurer.go
  pkg/webhook/controlplaneexposure/ensurer_test.go
Labels: area/dev-productivity, kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#759 Support for Kubernetes v1.27
  README.md
  charts/images.yaml
  pkg/webhook/controlplane/ensurer.go
  pkg/webhook/controlplane/ensurer_test.go
Labels: area/open-source, area/usability, exp/intermediate, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/m, topology/garden, topology/seed, topology/shoot, merge/squash
