Repository gardener/gardener-extension-provider-aws, pull requests merged in 2023-10, with the labels that each got.

#813 Support for Kubernetes v1.28
  README.md
  imagevector/images.yaml
Labels: area/open-source, area/usability, exp/intermediate, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs, topology/garden, topology/seed, topology/shoot, merge/squash

#810 update image definitions
  imagevector/images.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#795 Introduce the use of central manifest
  .ci/verify
  .docforge/manifest.yaml
  Makefile
Labels: area/documentation, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/lgtm, size/s

#818 fix: Concourse build badge URL
  README.md
Labels: area/documentation, kind/cleanup, needs/ok-to-test, needs/review, platform/aws, size/xs

#817 Update external-snapshotter to v6.3.1
  imagevector/images.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#819 add readiness check
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-validation-webhook-deployment.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs
