Repository gardener/gardener-extension-provider-aws, pull requests merged in 2023-08, with the labels that each got.

#786 Add `gardener-scheduler` region config example
  example/60-gardener-scheduler-region-configmap.yaml
Labels: kind/enhancement, needs/ok-to-test, platform/aws, reviewed/lgtm, size/l, area/scalability

#787 remove limits from system critical components
  charts/internal/machine-controller-manager/seed/values.yaml
  charts/internal/seed-controlplane/charts/aws-custom-route-controller/values.yaml
  charts/internal/seed-controlplane/charts/aws-load-balancer-controller/values.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/s

#789 Update region config example
  example/60-gardener-scheduler-region-configmap.yaml
Labels: kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, platform/aws, size/xl, area/scalability

#792 update timeout for release pipeline
  .ci/test-integration.sh
Labels: kind/regression, needs/ok-to-test, needs/review, platform/aws, size/xs, area/testing

#793 Correct persona for end user tutorial
  .docforge/manifest.yaml
Labels: needs/review, reviewed/ok-to-test, size/xs

#794 update ebs driver
  charts/images.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#790 No caching of secrets
  cmd/gardener-extension-provider-aws/app/app.go
Labels: area/control-plane, area/cost, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs
