Repository gardener/gardener-extension-provider-aws, pull requests merged in 2024-01, with the labels that each got.

#848 Bump aws-custom-route-controller from v0.7.0 to v0.8.0
  imagevector/images.yaml
Labels: area/control-plane, kind/task, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#851 Fix leader election of admission controller
  cmd/gardener-extension-admission-aws/app/app.go
Labels: area/security, kind/bug, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#855 update ebs driver and configuration
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-deployment.yaml
  imagevector/images.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/review, platform/aws, size/xs

#857 Fix hook-me script
  Makefile
  hack/dev-setup-admission-aws.sh
  hack/hook-me.sh
Labels: area/dev-productivity, kind/regression, needs/ok-to-test, platform/aws, reviewed/lgtm, size/m

#856 switch from public ecr to artifact registry for ipv6 support
  imagevector/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, reviewed/do-not-merge, size/xs

#858 Update image build rules
  Makefile
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#863 update ccm images
  imagevector/images.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#864 fix Makefile flag
  Makefile
Labels: area/dev-productivity, kind/regression, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#862 add nat-gateway ips
  .ci/hack/set_dependency_version
  example/20-crd-extensions.gardener.cloud_infrastructures.yaml
  go.mod
  go.sum
  pkg/controller/infrastructure/actuator_reconcile.go
  pkg/controller/infrastructure/actuator_restore.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/s

#865 Revert "switch from public ecr to artifact registry for ipv6 support"
  imagevector/images.yaml
Labels: area/control-plane, kind/regression, needs/ok-to-test, needs/review, platform/aws, size/xs

#867 Revert "Revert "switch from public ecr to artifact registry for ipv6 …
  imagevector/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#868 Add comment to images.yaml
  imagevector/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#869 Vendor gardener/gardener@v1.87.0
  .ci/hack/component_descriptor
  go.mod
  go.sum
Labels: area/open-source, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/s

#870 Fix csi-volume-modifier deployment after update to v0.1.3
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-deployment.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#872 Drop Machine Controller Manager management
  charts/gardener-extension-provider-aws/templates/clusterfilters-logging.yaml
  charts/internal/machine-controller-manager/seed/Chart.yaml
  charts/internal/machine-controller-manager/seed/mcm-monitoring-dashboard.json
  charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml
  charts/internal/machine-controller-manager/seed/templates/clusterrolebinding.yaml
  charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/machine-controller-manager/seed/templates/poddisruptionbudget.yaml
  charts/internal/machine-controller-manager/seed/templates/service.yaml
  charts/internal/machine-controller-manager/seed/templates/serviceaccount.yaml
  charts/internal/machine-controller-manager/seed/templates/vpa.yaml
  charts/internal/machine-controller-manager/seed/values.yaml
  charts/internal/machine-controller-manager/shoot/Chart.yaml
  charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/templates/clusterrolebinding-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/values.yaml
  example/controller-registration.yaml
  imagevector/images.yaml
  pkg/aws/types.go
  pkg/controller/worker/machine_controller_manager.go
Labels: area/open-source, kind/cleanup, needs/ok-to-test, needs/review, needs/second-opinion, platform/aws, reviewed/lgtm, size/xl

#873 Support for Kubernetes v1.29
  README.md
  imagevector/images.yaml
Labels: area/open-source, area/usability, exp/intermediate, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs, topology/garden, topology/seed, topology/shoot, merge/squash
