Repository gardener/gardener-extension-provider-aws, pull requests merged in 2024-07, with the labels that each got.

#992 rm failing preStop hook
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#994 [admission] Add `priorityClassName`
  charts/gardener-extension-admission-aws/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-aws/values.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, needs/review, platform/aws, size/xs

#998 Update k8s v1.30 conformance test coverage
  README.md
Labels: area/open-source, kind/enhancement, needs/ok-to-test, needs/review, platform/aws, size/xs

#993 Remove leftover from prior cleanup
  pkg/admission/validator/shoot.go
Labels: kind/cleanup, needs/ok-to-test, needs/review, platform/aws, reviewed/ok-to-test, size/xs

#1007 Upgrade machine-controller-manager-provider-aws on release-branch
  imagevector/images.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#853 Inserts `Architecture` from worker to machineclass
  charts/internal/machineclass/templates/machineclass.yaml
  charts/internal/machineclass/values.yaml
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: area/control-plane, kind/api-change, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/lgtm, reviewed/do-not-merge, size/s

#1012 Publish Helm charts as OCI artifacts
  .ci/pipeline_definitions
Labels: area/delivery, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/s

#1019 update vpa crd
  example/20-crd-vpa.yaml
Labels: kind/technical-debt, needs/ok-to-test, needs/review, needs/second-opinion, platform/aws, size/xl, area/testing
