Repository gardener/gardener-extension-provider-aws, pull requests merged in 2024-12, with the labels that each got.

#1153 docs: Repeat notice of manual shoot reconciliation
  docs/usage/usage.md
Labels: area/documentation, kind/enhancement, kind/cleanup, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#1158 Use ipv6 CIDR in ID string only for IPv6 only subnets.
  pkg/controller/infrastructure/infraflow/reconcile.go
Labels: area/networking, kind/bug, needs/ok-to-test, needs/review, platform/aws, size/xs

#1160 in IPv6 and dual stack shoot cluster external load balancers will get…
  pkg/webhook/shoot/loadbalancer_service.go
  pkg/webhook/shoot/loadbalancer_service_test.go
  pkg/webhook/shoot/mutator.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, platform/aws, size/m

#1163 [Release v1.59] Fix subnet migration patch
  pkg/controller/infrastructure/infraflow/reconcile.go
Labels: area/networking, kind/bug, needs/ok-to-test, needs/review, platform/aws, size/xs

#1161 fix: use UDP for upstream DNS by default
  pkg/admission/mutator/shoot.go
  pkg/admission/mutator/shoot_test.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, platform/aws, size/s

#1169 Use Subresource to mutate NamespacedCloudProfile status
  pkg/admission/mutator/webhook.go
Labels: area/usability, kind/bug, needs/ok-to-test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#1172 [cherry-pick: v1.59] Use Subresource to mutate NamespacedCloudProfile status
  pkg/admission/mutator/webhook.go
Labels: area/usability, kind/bug, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#1168 set primary-ip-family flag for aws-ipam-controller
  charts/internal/seed-controlplane/charts/aws-ipam-controller/templates/deployment.yaml
  charts/internal/seed-controlplane/charts/aws-ipam-controller/values.yaml
  imagevector/images.yaml
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, platform/aws, size/xs

#1176 Update gardener to v1.110.0
  example/20-crd-druid.gardener.cloud_etcds.yaml
  example/20-crd-extensions.gardener.cloud_workers.yaml
  go.mod
  go.sum
  pkg/cmd/options.go
Labels: area/usability, kind/cleanup, needs/ok-to-test, needs/review, platform/aws, size/m

#1179 Remove VPA for the csi-driver-node DaemonSet
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
Labels: kind/enhancement, needs/ok-to-test, needs/review, platform/aws, size/s, area/auto-scaling

#1175 Set IPv4 CIDR to empty string for IPv6 only shoots.
  pkg/controller/infrastructure/infraflow/reconcile.go
Labels: area/networking, kind/bug, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs
