Repository gardener/gardener-extension-provider-aws, pull requests merged in 2025-09, with the labels that each got.

#1462 add fixes for gha integration tests
  .github/workflows/run-integrationtests.yaml
Labels: needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#1437 Improve Load Balancer usage docu
  docs/usage/usage.md
Labels: area/quality, kind/enhancement, needs/review, platform/aws, size/xs

#1454 Add generation for `Extension` example
  Makefile
  example/doc.go
  example/extension.yaml
  example/extension/base/extension.yaml
  example/extension/base/kustomization.yaml
  example/extension/kustomization.yaml
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/lgtm, size/m

#1458 [GEP-33] Capabilities based MachineClass creation
  hack/api-reference/api.md
  pkg/admission/validator/cloudprofile.go
  pkg/admission/validator/namespacedcloudprofile.go
  pkg/admission/validator/shoot.go
  pkg/admission/validator/shoot_test.go
  pkg/apis/aws/helper/capabilities.go
  pkg/apis/aws/helper/helper.go
  pkg/apis/aws/helper/helper_test.go
  pkg/apis/aws/types_cloudprofile.go
  pkg/apis/aws/types_worker.go
  pkg/apis/aws/v1alpha1/types_worker.go
  pkg/apis/aws/v1alpha1/zz_generated.conversion.go
  pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/aws/validation/cloudprofile.go
  pkg/apis/aws/validation/cloudprofile_test.go
  pkg/apis/aws/validation/worker.go
  pkg/apis/aws/zz_generated.deepcopy.go
  pkg/controller/worker/machine_images.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
  pkg/webhook/infrastructure/mutate.go
Labels: area/control-plane, kind/api-change, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, platform/aws, size/xl, ai/review

#1472 Add conformance test badge for Kubernetes v1.33
  README.md
Labels: needs/ok-to-test

#1461 [GEP-26] Enable validation of `seed.spec.backup.credentialsRef` and `backupBucket.spec.credentialsRef`
  Makefile
  pkg/admission/decode.go
  pkg/admission/validator/backupbucket.go
  pkg/admission/validator/backupbucket_test.go
  pkg/admission/validator/credentialsbinding.go
  pkg/admission/validator/credentialsbinding_test.go
  pkg/admission/validator/seed.go
  pkg/admission/validator/seed_test.go
  pkg/admission/validator/webhook.go
  pkg/admission/validator/workloadidentity.go
  pkg/admission/validator/workloadidentity_test.go
  pkg/apis/aws/helper/scheme.go
  pkg/apis/aws/helper/scheme_test.go
  pkg/apis/aws/validation/backupbucket.go
  pkg/apis/aws/validation/backupbucket_test.go
  pkg/apis/aws/validation/helper.go
  pkg/apis/aws/validation/helper_test.go
  pkg/controller/backupentry/actuator_test.go
  pkg/controller/infrastructure/actuator.go
  pkg/webhook/cloudprovider/add.go
  pkg/webhook/cloudprovider/ensurer.go
  pkg/webhook/cloudprovider/ensurer_test.go
Labels: area/security, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xl, area/ipcei

#1482 Add new workflow for build/CD on PRs
  .github/workflows/non-release.yaml
  .github/workflows/pullrequest-trust-helper.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#1485 update aws-ipam-controller to v0.7.0
  imagevector/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs
