Repository gardener/gardener-extension-provider-aws, pull requests merged in 2025-10, with the labels that each got.

#1486 `chore:` Update EFS CSI driver image to v2.1.12
  imagevector/images.yaml
Labels: area/quality, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/lgtm, size/xs

#1492 Clean up MCM RBAC resource migrations
  cmd/gardener-extension-provider-aws/app/app.go
  cmd/gardener-extension-provider-aws/app/migrations.go
Labels: area/security, kind/cleanup, needs/ok-to-test, platform/aws, reviewed/lgtm, size/s

#1499 Add OWNERS files
  OWNERS
  OWNERS_ALIASES
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#1495 Automatically close release milestones
  .github/workflows/close-milestone.yaml
  .github/workflows/release.yaml
Labels: area/quality, kind/enhancement, needs/ok-to-test, platform/aws, reviewed/lgtm, size/s
