Repository gardener/gardener-extension-provider-aws, pull requests merged in 2025-06, with the labels that each got.

#1351 [release-v1.62] cherry pick of #1349: Fix deleting managed elastic IP
  example/controller-registration.yaml
  pkg/controller/infrastructure/infraflow/reconcile.go
Labels: area/quality, kind/bug, needs/ok-to-test, needs/review, platform/aws, size/s

#1344 change exported consts to unexported
  test/integration/backupbucket/backupbucket_test.go
  test/integration/backupbucket/helper_test.go
Labels: kind/test, needs/review, platform/aws, reviewed/ok-to-test, size/xs, area/testing

#1355 add gosec-report to ocm-component-descriptors
  .github/workflows/build.yaml
  .ocm/base-component.yaml
Labels: area/delivery, kind/bug, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/s

#1365 run `make generate` for release- and bump-commits
  .ci/prepare_release
  .github/actions/prepare-release/action.yaml
  .github/workflows/build.yaml
  .github/workflows/release.yaml
Labels: area/delivery, kind/bug, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs

#1363 Set AWS_REGION for cloud controller manager
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/deployment.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
  pkg/webhook/cloudprovider/ensurer.go
  pkg/webhook/cloudprovider/ensurer_test.go
Labels: area/quality, kind/bug, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/s

#1356 Use backup operator secret for backupbucket integration test
  .ci/testruns/default/templates/testrun.yaml
  .gitignore
  .test-defs/backupbucket-test.yaml
  test/integration/backupbucket/helper_test.go
Labels: kind/test, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/testing

#1373 [GEP-26] Update seed backup docs to use credentialsRef field
  docs/operations/operations.md
Labels: area/documentation, area/security, kind/enhancement, needs/review, platform/aws, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/ipcei

#1375 Remove `gardener/gardener-maintainers` from `CODEOWNERS` file
  CODEOWNERS
Labels: reviewed/ok-to-test
